language: python
before_install:
- sudo add-apt-repository --yes ppa:fontforge/fontforge
- sudo apt-get update -qq
- sudo apt-get install python-fontforge
- cp /usr/lib/python2.7/dist-packages/fontforge.* "$HOME/virtualenv/python2.7.8/lib/python2.7/site-packages"
install:
- pip install git+https://github.com/behdad/fontTools.git
- pip install git+https://github.com/googlefonts/fontbakery-cli.git
- pip install jinja2
script: PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH fontbakery.py .
branches:
  only:
  - master
after_script:
- rm -rf builds/build/sources builds/build/build.state.yaml
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH bakery-report.py builds/build
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH travis-deploy.py
env:
  global:
    secure: mkBiH3zqOoY9pv/cTRVaSH+bE6L7jQqsiJiFY3WrGpyKIvsJE3jisGEJsZ6zvppkZt6KaOFq/NXs3BWzRWFe+cj0KOL+ElJS3N0ydUag02sP1T782n3eCw9rFiJHHPppBf0jcb/EwUf68LfFcpiJSGAgxBLRRoBm593qv54vOlk=
